spring.application.name=cinema

spring.datasource.url=jdbc:mysql://localhost:3306/db_cinema
spring.datasource.username=root
spring.datasource.password=11131427

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true